import type { Match } from "@/components/dashboard/MatchCard";

export const liveMatches: Match[] = [
  {
    id: "l1",
    league: "Premier League",
    leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    home: "Arsenal",
    away: "Chelsea",
    homeScore: 2,
    awayScore: 1,
    minute: "67",
    isLive: true,
    hasStream: true,
    odds: { home: 1.85, draw: 3.4, away: 4.2 },
  },
  {
    id: "l2",
    league: "La Liga",
    leagueFlag: "🇪🇸",
    home: "Real Madrid",
    away: "Barcelona",
    homeScore: 1,
    awayScore: 1,
    minute: "54",
    isLive: true,
    hasStream: true,
    odds: { home: 2.1, draw: 3.2, away: 3.1 },
  },
  {
    id: "l3",
    league: "Serie A",
    leagueFlag: "🇮🇹",
    home: "Juventus",
    away: "Inter",
    homeScore: 0,
    awayScore: 2,
    minute: "72",
    isLive: true,
    odds: { home: 5.5, draw: 3.8, away: 1.55 },
  },
  {
    id: "l4",
    league: "Bundesliga",
    leagueFlag: "🇩🇪",
    home: "Bayern Munich",
    away: "Dortmund",
    homeScore: 3,
    awayScore: 0,
    minute: "41",
    isLive: true,
    hasStream: true,
    odds: { home: 1.25, draw: 6.5, away: 9.0 },
  },
  {
    id: "l5",
    league: "Ligue 1",
    leagueFlag: "🇫🇷",
    home: "PSG",
    away: "Marseille",
    homeScore: 1,
    awayScore: 0,
    minute: "23",
    isLive: true,
    odds: { home: 1.65, draw: 3.9, away: 4.8 },
  },
  {
    id: "l6",
    league: "Eredivisie",
    leagueFlag: "🇳🇱",
    home: "Ajax",
    away: "PSV",
    homeScore: 2,
    awayScore: 2,
    minute: "81",
    isLive: true,
    hasStream: true,
    odds: { home: 2.4, draw: 3.1, away: 2.7 },
  },
];

export const upcomingMatches: Match[] = [
  {
    id: "u1",
    league: "Champions League",
    leagueFlag: "🏆",
    home: "Man City",
    away: "Liverpool",
    startTime: "20:45",
    isLive: false,
    odds: { home: 2.05, draw: 3.5, away: 3.4 },
  },
  {
    id: "u2",
    league: "Europa League",
    leagueFlag: "🏆",
    home: "Roma",
    away: "Leverkusen",
    startTime: "21:00",
    isLive: false,
    odds: { home: 2.8, draw: 3.3, away: 2.45 },
  },
  {
    id: "u3",
    league: "Premier League",
    leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    home: "Tottenham",
    away: "Newcastle",
    startTime: "22:00",
    isLive: false,
    odds: { home: 1.95, draw: 3.6, away: 3.8 },
  },
  {
    id: "u4",
    league: "La Liga",
    leagueFlag: "🇪🇸",
    home: "Atletico Madrid",
    away: "Sevilla",
    startTime: "22:30",
    isLive: false,
    odds: { home: 1.55, draw: 4.0, away: 5.5 },
  },
  {
    id: "u5",
    league: "NBA",
    leagueFlag: "🇺🇸",
    home: "Lakers",
    away: "Celtics",
    startTime: "01:00",
    isLive: false,
    odds: { home: 2.25, draw: 14.0, away: 1.7 },
  },
  {
    id: "u6",
    league: "ATP Masters",
    leagueFlag: "🎾",
    home: "Alcaraz",
    away: "Djokovic",
    startTime: "16:30",
    isLive: false,
    odds: { home: 1.9, draw: 12.0, away: 1.95 },
  },
  {
    id: "u7",
    league: "Serie A",
    leagueFlag: "🇮🇹",
    home: "Napoli",
    away: "Milan",
    startTime: "23:00",
    isLive: false,
    odds: { home: 2.2, draw: 3.4, away: 3.0 },
  },
  {
    id: "u8",
    league: "NHL",
    leagueFlag: "🏒",
    home: "Maple Leafs",
    away: "Rangers",
    startTime: "02:00",
    isLive: false,
    odds: { home: 1.85, draw: 4.2, away: 3.6 },
  },
];
